apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - otel-collector-configmap.yaml
  - otel-collector-deployment.yaml
  - otel-collector-service.yaml
  - prometheus-rbac.yaml
  - openobserve-prometheus-secret.yaml
  - prometheus-configmap.yaml
  - prometheus-deployment.yaml
  - prometheus-service.yaml
  - node-exporter-daemonset.yaml
  - kube-state-metrics-rbac.yaml
  - kube-state-metrics-deployment.yaml
  - kube-state-metrics-service.yaml
  - grafana-secret.yaml
  - grafana-datasource-configmap.yaml
  - grafana-dashboard-provider-configmap.yaml
  - grafana-dashboard-json-configmap.yaml
  - grafana-deployment.yaml
  - grafana-service.yaml
  - ingress.yaml
